#!/bin/bash

# Name:           kickstart
# Author:         Jay Kumar
# Date Written:   23th October 2020
# Last Modified:  23rd October 2020
# Purpose:        Kickstart all build and performance monitoring scripts
# Description:    Automated script to kickstart the entire project. The script fetches all files from github that are necessary and starts the kernel build and monitoring.

declare -r REPO="git@github.com:jaykch/linux-kernel-build"
declare -r DIR="./project"
declare -r SSH_KEY="ADD SSH KEY HERE"

# verify ssh configuration directory exists
if [[ ! -d ~/.ssh ]]; then
    echo "Creating .ssh"
    mkdir ~/.ssh
    chmod 0700 ~/.ssh
fi
# verify we have a github ssh key
if [[ ! -e ~/.ssh/github ]]; then
    echo "Adding SSH key"
    echo "$SSH_KEY" > ~/.ssh/github
    chmod 0600 ~/.ssh/github
fi

# verify ssh config has an entry for github
if ! grep -q "Host github.com" ~/.ssh/config; then
    echo "Adding GitHub SSH configuration"
    echo "Host github.com" >> ~/.ssh/config
    echo "IdentityFile ~/.ssh/github" >> ~/.ssh/config
fi

# clone the repo and start the build
git clone "$REPO" "$DIR"
cd "$DIR" || exit 255
chmod +x build_kernel performance_monitor status_led
./build_kernel

