#!/bin/bash

declare -r REPO="git@github.com:jaykch/linux-kernel-build"
declare -r DIR="./project"
declare -r SSH_KEY="-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAOwz8bL7
2K6e5OAKDPYb4zAAAAEAAAAAEAAAIXAAAAB3NzaC1yc2EAAAADAQABAAACAQCqbtfe9ELh
PbV1Aedn/3752Eq2GAyVE/m2IWGZHAMfmOA5S7KT841dtbHxlFqn2gWZMHIzn7JoXIMHDs
Q9CkPwLgphYj1jGB4Ir4GzK4l8OfJkDcNUa6Jdner//PqfbyRPfAzugYCAuCf0KQLfq9su
mOpAMa1DcMmdKxV9rSXPkrBIivrSHCYeeW4AmfwvWuV0DhuliyeKni0GkzXpSEN28mCQ3j
B+yeGOT/cIEdFn0O19xvVCLhTQpdwnRE81F9JLjdf544NfUPRsWD+SngeBx4SvaFzW7PaD
jF1uqBuE9b9xchtqKeZX5mzodxj49XOd8aiba/vIPo1gSMQZTUDOy6LUOGbGERZYBLOWW+
6YZSgzlYgrmhnJg9cBJ7+iIGDh2W9VlW5w2YzH/J+avyMBdYoNY9fQzr/ymZ2CF4lpAJ5K
EVAdksWyHd80DGKREujo5f6XHSlFsE5ot9zf5zaNysS3D8XR5O23/Y8xLd1aLBxvT8Dpot
o/o3bC06Gixq0NqFYyVnu7P5yl/Vdhe9TNLBrVOr4FW39opYbFuyQP0lqtdVWbC29bbwYV
csyK141wb8TJj8zx0RmYETxIiGXr1wye70Hs+a01FB5Aqfyl1WKFZv2cfWMekDGR+0aXvX
bWbARyKKSO/uJxD0xbdLjAScVU6hvbvbLoLOUW8xFe9QAAB2DLV3DrVsUcqJAXwfGpoPtW
DGM6csnYQ7YOOz5evoLoF87ka+2UZKQcamARQhB5UoWpjC0ZrWLyaF1CVfrJi9t69YMNQy
1OqQW8qVszpjWNAm7YWk1RzrhtPVXskn7/Nau4prsgDb7BqArq7xv24h+44kiu5Uy2R/LQ
KpnV2QnX/p7nmmmPFzIrPoBDVXmoxGh7LXP3dsf+j1SoSE5R9zh0MvpdztomsjSBOognXb
0NLu2qVJosXIpW/6b/ejpgOnlCjiD5pAzrf48ZeaabkEU/z3j1CBxfj1uV65BS2o5PGEf3
lvVVciapb1A8Yv8b79D+xemVF3K1V0/iTLte0+gyWaqxVnW7Zpk/QzuTO/Gpa148AQkts9
Iq/HT8AUY4UYLwHY+HJf9KISl5mL5SCpLJ/RlfHT8TgUsZFRSIYuSyOa3BS1eUcR9GnBmR
doTD5yMu5a3PvbnZR68lWN/5OikX54Ydo/nSQAk+s3GbOi+YL7XZu0SLPQ0ZADKGof2QRx
VGgdfzttdXhMtv9gjVxxabMxugy5D6gHRuJmb1YjnBDUv3AAFKAhy8Eg3v7zJ5J6Qtli2R
Jy0JUusP07iog80N+cp4Ptk/rY0xiMZZeizG74QtcOC2TEqWWQB4C3Q/0vBZZZBOm+PM6C
gCJEMkUSOxMin/OAJGuKcvZlnwUgJBeqp2eHZsK3OoPdDb9Fdy7iHJQHN5aHOKe3GC1dQK
KgpoO7qdL+0cI/vAHDQx12j45YCBaRXvLwiMdQN1b233fgZMeDWzK8sZNQH8WyRnsJWb5J
Fh9r+KzZrRmIHxWw1uqlbmmpSkfugq08x68rOuos22IeyBohlhUyDm1K/K0BhFGF/8dGT8
qXMgG3+2UPn3l0ZVKrbCKWhp3XFu7tXua57RK65W7EKLcQZy7tIlPbHlrGsWjtnWU5Cauc
QnTLgFTcoWw3hqMSfiUBPowBH0EV47IXip9Dl6mC5aaTQeBehEYSkbAXOf4JhLLRauM6qh
rayeUjqCA2h4+wXF7Q6IJr5uL8PHHSbW9Njyy9hcKg13Bh1e+lMOzjBQ9NPdItBB7zW/jg
dQ1tyOVmOAyq9Hgj7bH0MvbsmmF1B4aXYP1wWepoXqb5ZnGsFrjeakCM1Kli+QLgeX1g+k
SZtxgHIFKFhwslrUzpfTtkDiLhTWFAW4Q+I8+N1y/2+w9NVhQOhRIdwftnesmPPPhX8J9J
sgaGBngSzHXrTjV/hqFQocDVrSuFwhN5cOg8J2TidYrjUc9ZKpeevnwYp6698GFb2nk2PK
C2q+sr0dZmISOr61mwO352+WzWkOg+0EfmRIiPElq7Ko5UB+y8jI2ZVqHgiKPm0Z+VA7zv
LfJJ72NrPyi6476W2mWKGqPFAXeM3o4kENvYMfwHdNK5ERly1ClEcQwYvVV9NeyGe1PmSp
eCg995RD9P+o4qJPhJqrDEy8XG2nJNY3J7aP7ojAnC0sBFy4xgctBS3dwpekEeCtD8L6v4
9LafDCEfmY9EnZQuVq5cLy6tBfFzLpOE8MBgt75LbOvxn/GLmCwg3sowq789mYZIrk7wZx
pKhbYX+ch3eQ3ANtBJxq078jsmCMcs0sozWfnKY62mchQy1hj+M1zYrnFJbPal4GzNkAhg
GcGPwqOiM1F33P3UOo8ESkkEULX6GGWwLrq1QTw9s36fC3B2nMbaLedt8cFCPgo8Rjm6lm
8E8c4GolJyeqWBcHwaisnF3RuSGBvHv9c7oXQEgnylMUElUbFHfw4RNfh8mtSZe6i3CWq2
qdioIJdD+7dtxbWKPLHBAxpRCQ+YN8iRgK7+d3lYSXDxIsSuj7lmhcSD1AD4m6qfzYsvKp
syInMVH/Cx0icmiCasPWCmdngExJCGPmh62Vyo8OXrTS/JVnLdipo+vK2k+Dv1ccDkFE7O
PBl3SJozZl+wmhETfs5YdBqobnRlzQfWUmZx4XMTYu5twCWpKYHNFbo+WabHhMXghq41cQ
szRtBI/f2DYxReyzcIny14CcUxxfqAJA+2CnI4BHxBD9iKvIu4jVgKtVLqicd2XSpmkM42
Par5yi9SpuiQ55CklKyideQS3pQyUscmQKLjznYmamTWtHpcNOxqhKcUs3q+debWma7I0q
oCX5ySHG/3dRdq2qVgzj9W2jMV45HUGXLt1yUhm1sfXuApiUT6axhEfZfZgJsoh/14zCwr
/1hnwA6me/MRIqnUEWLfB5pQ3oIIhAgq05pAEJOrPNsjH7VX7wUy3BAGaL+51Rx0rSSyY3
B3YhPOEaA4QAhapdTdq3eCJWaFKIySY5IFUxVq6gnR44chBsHtqsBEqmfauPV9ne4AHgOi
8uCD53zNpbBdD+hKUTiLB3v5B2JW9k8g08mPxSVhGsfcENWcsW9HxA1YqMfM99KK3f0VUv
1jE/qlk3I4APgmXxO+vooayeJJhfeSn9nLcLYu2w2YXu1JDDXza22OC+ZokP2fJwgg2CkN
p0QUx02mKyqe3O9o0+Y4r/dOsw78+toVW8dd9ByuG3JNqs
-----END OPENSSH PRIVATE KEY-----"

# verify ssh configuration directory exists
if [[ ! -d ~/.ssh ]]; then
    echo "Creating .ssh"
    mkdir ~/.ssh
    chmod 0700 ~/.ssh
fi
# verify we have a github ssh key
if [[ ! -e ~/.ssh/github ]]; then
    echo "Adding SSH key"
    echo "$SSH_KEY" > ~/.ssh/github
    chmod 0600 ~/.ssh/github
fi

# verify ssh config has an entry for github
if ! grep -q "Host github.com" ~/.ssh/config; then
    echo "Adding GitHub SSH configuration"
    echo "Host github.com" >> ~/.ssh/config
    echo "IdentityFile ~/.ssh/github" >> ~/.ssh/config
fi

# clone the repo and start the build
git clone "$REPO" "$DIR"
cd "$DIR" || exit 255
chmod +x build_kernel performance_monitor status_led
./build_kernel

